BLOCKED_TAGS = [
    "creampie",
    "anal sex",
    "blow jobs",
    "bdsm",
    "breeding",
    "explicit sexual content",
    "gangbang",
    "gay sex",
    "lesbian sex",
    "oral sex",
    "porn",
    "rape",
    "sex",
    "smut",
    "underage sex - freeform",
    "vaginal sex",
    "nipple play",
    "dirty talk",
    "double penetration",
    "size kink",
    'anal sex',
    'blow jobs',
    'bdsm',
    'breeding',
    'creampie',
    'explicit sexual content',
    'gangbang',
    'gay sex',
    'lesbian sex',
    'mpreg',
    'oral sex',
    'porn',
    'rape',
    'sex',
    'smut',
    'underage sex - freeform',
    'vaginal sex',
    'nipple play',
    'deepthroating',
    'dirty talk',
    'double penetration',
    'size kink'
]
